### ISSUE TITLE
Upgrade to python 3.12 broke everything 🔴 

### ISSUE THREAD

**Issue by MDGrey33** [MDGrey33/Nur#13]
After the migration to python 3.12 using poetry, everything worked fine till the debugger stopped working
Cant start the debugger on pycharm the wrapper out of nowhere can’t deal with any of the (deprecated) packages
A few options I might pursue:
find-out whats wrong with the wrapper and fix it (I’m hoping this works :slightly_smiling_face:  other scenarios are ugly)
find alternatives to the supposedly deprecated packages (almost everything might as well rewrite the whole thing)
OpenAI
ChromaDB
Confluence
Persisqueue
go to a python version that supports all those libraries and work my way out of them
/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/bin/python3.12 -X pycache_prefix=/Users/roland/Library/Caches/JetBrains/PyCharmCE2023.3/cpython-cache /Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 54632 --file /Users/roland/code/Nur/main.py 
Connected to pydev debugger (build 233.13763.11)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/roland/code/Nur/main.py", line 2, in <module>
    from confluence_integration.retrieve_space import get_space_content, choose_space
  File "/Users/roland/code/Nur/confluence_integration/retrieve_space.py", line 5, in <module>
    from atlassian import Confluence
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/lib/python3.12/site-packages/atlassian/__init__.py", line 2, in <module>
    from .bitbucket import Bitbucket
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/lib/python3.12/site-packages/atlassian/bitbucket/__init__.py", line 13, in <module>
    class Bitbucket(BitbucketBase):
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/lib/python3.12/site-packages/atlassian/bitbucket/__init__.py", line 1726, in Bitbucket
    @deprecated(version="1.15.1", reason="Use get_pull_request()")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/lib/python3.12/site-packages/deprecated/classic.py", line 276, in deprecated
    @wrapt.decorator(adapter=adapter)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/lib/python3.12/site-packages/wrapt/decorators.py", line 427, in decorator
    return _build(wrapper, _wrapper, adapter=decorator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-8mBi3D3r-py3.12/lib/python3.12/site-packages/wrapt/decorators.py", line 239, in _build
    return AdapterWrapper(wrapped=wrapped, wrapper=wrapper,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle/pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle/pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
ValueError: wrapper has not been initialized

Process finished with exit code 1

**Comment by MDGrey33** [comment]
Debugger back on track
Pycharm local files were the issue
I deleted all pycharm files 
deleted poetry.lock
did poetry install 
then poetry lock, 
did poetry env info then pointed the interpreter to use the interpreter specified in the output to set the interpreter in pycharm and debugging worked fine
