### ISSUE TITLE
When running ./main.py for the first time error with database file permission

### ISSUE THREAD

**Issue by MDGrey33** [MDGrey33/Nur#7]
When running ./main.py for the first time error with the database file permission

`/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/bin/python3.12 /Users/roland/code/NurB/Nur/main.py 
Traceback (most recent call last):
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/roland/code/NurB/Nur/main.py", line 2, in <module>
    from confluence_integration.retrieve_space import get_space_content, choose_space
  File "/Users/roland/code/NurB/Nur/confluence_integration/retrieve_space.py", line 7, in <module>
    from database.nur_database import mark_page_as_processed
  File "/Users/roland/code/NurB/Nur/database/nur_database.py", line 395, in <module>
    Base.metadata.create_all(engine)
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 5825, in create_all
    bind._run_ddl_visitor(
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3232, in _run_ddl_visitor
    with self.begin() as conn:
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3222, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3258, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2422, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roland/Library/Caches/pypoetry/virtualenvs/nur-n7sGK3Wc-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Process finished with exit code 1

`

**Comment by MDGrey33** [comment]
Resolved by adding the content folder with its subfolders database file_system and transactional and adding .include in them to make sure they remain in the structure in git.
This is a good enough solution but chances are by mistake the .include file might be deleted and the error might happen again.
I might eventually add a script that creates those folders if they are missing.
